apps/website/urls.py
"""
    Url's de la aplicación website
"""

from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.views import (PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView)

from apps.website.views import (
    ClienteInicioSession, ComprasLista, DashboardCliente, DesignerLounge,
    DesignerLoungeRegistro, DetallePublicacion, IndexWebsite, ProcesoCompra,
    ProveedorInicioSession, RegistroCliente, ShoppingCart,
    VistaFavoritosCliente, add_address_user, agregar_items_carro, add_favorito,
    VistaResultados)

urlpatterns = [
    url(r'^$', IndexWebsite.as_view(), name='index_website'),
    url(
        r'^designer_lounge/$',
        login_required(
            DesignerLounge.as_view(),
            login_url=reverse_lazy('website:inicio_sesion_proveedor')),
        name='designer_lounge'),
    url(
        r'^designer_lounge/registrar$',
        DesignerLoungeRegistro.as_view(),
        name='designer_lounge_registro'),
    url(
        r'^sesion_proveedor/$',
        ProveedorInicioSession.as_view(),
        name='inicio_sesion_proveedor'),
    url(
        r'^inicio_sesion/$',
        ClienteInicioSession.as_view(),
        name='inicio_sesion'),
    url(r'^cerrar_sesion/$', LogoutView.as_view(), name='cerrar_sesion'),
    url(
        r'^cerrar_sesion/(?P<next_page>.*)/$',
        LogoutView.as_view(),
        name='cerrar_sesion_next'),
    url(
        r'^registro_cliente/$',
        RegistroCliente.as_view(),
        name='registro_cliente'),

    url(
        r'^usuarios/reset/password_reset',
        PasswordResetView.as_view(), {
            'template_name': 'email_forgot.html',
            'email_template_name': 'correo_cambio.html'
        },
        name='forgot_password'),
    # url(
    #     r'^usuarios/password_reset_done',
    #     password_reset_done,
    #     {'template_name': 'confirmacion_olvido_password.html'},
    #     name='password_ready'),
    # url(
    #     r'^usuarios/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
    #     password_reset_confirm, {'template_name': 'cambiar_password.html'},
    #     name='confirm_password_reset'),
    # url(
    #     r'^usuarios/reset/done',
    #     password_reset_complete, {'template_name': 'password_changed.html'},
    #     name='complete_password_reset'),
    url(r'^carrito_compra/$', ShoppingCart.as_view(), name='carrito_compra'),
    url(
        r'^comprar/$',
        login_required(
            ProcesoCompra.as_view(),
            login_url=reverse_lazy('website:inicio_sesion')),
        name='proceso_compra'),
    url(r'^busqueda/$', VistaResultados.as_view(),name='busqueda-resultados'),
    url(
        r'^detalle/(?P<pk>\d+)$',
        DetallePublicacion.as_view(),
        name='detalle_publicacion'),
    url(
        r'^dashboard/(?P<pk>\d+)$',
        login_required(
            DashboardCliente.as_view(),
            login_url=reverse_lazy('website:inicio_sesion')),
        name='dashboard_cliente'),
    url(r'^compras/$', ComprasLista.as_view(), name='lista_compras'),
    url(
        r'^favoritos/$',
        login_required(
            VistaFavoritosCliente.as_view(),
            login_url=reverse_lazy('website:inicio_sesion')),
        name='favoritos_cliente'),
    url(r'^comprar/guardar_direccion/$',
        login_required(
            add_address_user,
            login_url=reverse_lazy('website:inicio_sesion'))),
    url(
        r'^guardar_favorito/$',
        login_required(
            add_favorito, login_url=reverse_lazy('website:inicio_sesion')),
        name='add_favoritos'),
    url(r'^agregar_items_carro/$', agregar_items_carro, name='add_to_cart'),
]

vima/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from apps.administrador.views import cerrar_sesion
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    # url(r'^admin/', admin.site.urls), no se usara el admin de django
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'clave_formulario.html',
        'email_template_name': 'clave_correo.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'clave_enviado.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'clave_confirmar.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'clave_cambiada.html'},
        name='password_reset_complete'),


    url(r'^administrador/', include('apps.administrador.urls', namespace='administrador')),
    url(r'^inventario/', include('apps.inventario.urls', namespace='inventario')),
    url(r'^compras/', include('apps.compras.urls', namespace='compras')),
    url(r'^cuentas_pagar/', include('apps.cuentas_pagar.urls', namespace='cuentas_pagar')),
    url(r'^cerrar_sesion/$', cerrar_sesion, name='cerrar_sesion'),

    url(r'^', include('apps.website.urls', namespace='website'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/website/views.py
"""
    Vistas de la aplicación website
"""
import ast
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.http.response import JsonResponse
from django.shortcuts import HttpResponseRedirect, render
from django.utils.translation import ugettext_lazy as _
from django.views.generic import (CreateView, DetailView, ListView,
                                  TemplateView, UpdateView)

from apps.administrador.forms import UserCreateForm, UserUpdateForm
from apps.cuentas_pagar.forms import ProveedorForm
from apps.cuentas_pagar.models import Proveedores, Ciudades
from apps.inventario.models import Publicaciones, Categorias
from apps.website.forms import (CLIENTE_FORMSET, AgregarItemsCart, CompraForm,
                                PROVEEDOR_FORMSET, DireccionAdicional)
from apps.website.models import (Cliente, DetalleVentas, DireccionesCliente,
                                 Ventas, FavoritosCliente, CartItem)

from apps.website.classes import Cart, obtener_id_carro, obtener_items_carro, crear_carro, obtener_cantidad_items_carro
from django.db import transaction, IntegrityError


class IndexWebsite(TemplateView):
    """
        Vista principal del website VIMA.
    """
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        """Agrega al contexto la lista de proveedores diseñadores y los últimos productos."""
        context = super(IndexWebsite, self).get_context_data(**kwargs)
        context['proveedores_disenadores'] = Proveedores.objects.filter(
            activo=True, es_disenador=True)
        context['ultimos_productos'] = Publicaciones.objects.select_related(
            'id_producto')[:10]
        context['cantidad_items_carro'] = obtener_cantidad_items_carro(
            self.request)

        tags = []
        for t in Categorias.objects.filter(id_categoria_padre=None):
            tags.append(t.serializable_object())

        arbol_categorias = {}
        for categoria in Categorias.objects.filter(
                id_categoria_padre=1).order_by('id_categoria'):
            desc_categoria = categoria.descripcion
            hijos = categoria.get_all_children(categoria.id_categoria)
            for hijo in hijos:
                if hijo.descripcion != desc_categoria:
                    arbol_categorias.setdefault(desc_categoria,
                                                []).append(hijo.descripcion)
                else:
                    arbol_categorias.setdefault(desc_categoria, []).append('')

        context['cat_padres'] = arbol_categorias
        return context


class DesignerLounge(TemplateView):
    """
        Vista principal del area de designers de VIMA.
    """
    template_name = 'home_proveedor.html'


class DesignerLoungeRegistro(SuccessMessageMixin, CreateView):
    """
        Vista de registro de proveedores de VIMA.
    """
    model = User
    template_name = 'registro_proveedor.html'
    success_url = reverse_lazy('website:designer_lounge')
    form_class = UserCreateForm
    success_message = _('Proveedor %(nombre_empresa)s creado correctamente')

    def get(self, request, *args, **kwargs):
        """Redefinición de metodo ``get()`` para manejar el perfil de cliente."""
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        proveedor_form = PROVEEDOR_FORMSET()
        return self.render_to_response(
            self.get_context_data(form=form, proveedor_form=proveedor_form))

    def post(self, request, *args, **kwargs):
        """Redefinición de metodo ``post()`` para manejar el perfil de cliente."""
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        proveedor_form = PROVEEDOR_FORMSET(request.POST, request.FILES)
        if form.is_valid() and proveedor_form.is_valid(): 
            return self.form_valid(form, proveedor_form)
        else:  
            return self.form_invalid(form, proveedor_form)

    def form_valid(self, form, proveedor_form):
        """Redefinición de metodo ``form_valid()`` para manejar el perfil de cliente."""
        try:
            with transaction.atomic():
                self.object = form.save(commit=False)
                self.object.is_staff = False
                self.object.save()
                proveedor_form.instance = self.object
                nuevo_proveedor = proveedor_form.save(commit=False)
                nuevo_proveedor[
                    0].ciudad_direccion_envio = Ciudades.objects.get(
                        id_ciudad=self.request.POST.get(
                            "id_proveedores-0-ciudad_direccion_envio"))
                nuevo_proveedor[
                    0].ciudad_direccion_fiscal = Ciudades.objects.get(
                        id_ciudad=self.request.POST.get(
                            "id_proveedores-0-ciudad_direccion_fiscal"))
                nuevo_proveedor[0].save()
                messages.add_message(self.request, messages.INFO, _('Su registro ha sido exitoso'))
                return HttpResponseRedirect(self.get_success_url())
        except IntegrityError:
            return super(DesignerLoungeRegistro, self).form_invalid(
                form, proveedor_form)

    def form_invalid(self, form, proveedor_form):
        """Redefinición de metodo ``form_invalid()`` para manejar el perfil de cliente."""
        return self.render_to_response(
            self.get_context_data(form=form, proveedor_form=proveedor_form))


class RegistroCliente(SuccessMessageMixin, CreateView):
    """
        Vista de registro de clientes de VIMA.
    """
    model = User
    template_name = 'registro_cliente.html'
    success_url = reverse_lazy('website:inicio_sesion')
    form_class = UserCreateForm
    success_message = _('Usuario %(username)s creado correctamente')

    def get(self, request, *args, **kwargs):
        """Redefinición de metodo ``get()`` para manejar el perfil de cliente."""
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        cliente_form = CLIENTE_FORMSET()
        return self.render_to_response(
            self.get_context_data(form=form, cliente_form=cliente_form))

    def post(self, request, *args, **kwargs):
        """Redefinición de metodo ``post()`` para manejar el perfil de cliente."""
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        cliente_form = CLIENTE_FORMSET(request.POST)
        if form.is_valid() and cliente_form.is_valid():
            return self.form_valid(form, cliente_form)
        else:
            return self.form_invalid(form, cliente_form)

    def form_valid(self, form, cliente_form):
        """Redefinición de metodo ``form_valid()`` para manejar el perfil de cliente."""
        self.object = form.save(commit=False)
        self.object.is_staff = False
        self.object.save()
        cliente_form.instance = self.object
        cliente_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, cliente_form):
        """Redefinición de metodo ``form_invalid()`` para manejar el perfil de cliente."""
        return self.render_to_response(
            self.get_context_data(form=form, cliente_form=cliente_form))


class ProveedorInicioSession(TemplateView):
    """
        Vista inicio de sesión de clientes VIMA.
    """
    template_name = 'inicio_sesion_designer_lounge.html'

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return render(request, 'home_proveedor.html')
        else:
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            print('user')
            #TODO: cambiar orden de los mensajes
            if user is not None:
                print('user not none')
                if user.is_active and not user.is_staff:
                    login(request, user)
                    print('logueaado')
                    if request.GET:
                        print('get')
                        return HttpResponseRedirect(request.GET.get('next'))
                    else:
                        print('redirect') 
                        return HttpResponseRedirect(
                            reverse_lazy(
                                'website:inicio_sesion_proveedor',
                                kwargs={'pk': user.id}))
                else:
                    print('inactivo')
                    messages.add_message(request, messages.INFO,
                                         _('Cuenta de usuario inactiva'))
            else:
                print('contraseña')
                messages.add_message(
                    request, messages.INFO,
                    _('Nombre de usuario o contraseña no válido'))
        return HttpResponseRedirect(
            reverse_lazy('website:inicio_sesion_proveedor'))


class ClienteInicioSession(TemplateView):
    """
        Vista inicio de sesión de clientes VIMA.
    """
    template_name = 'inicio_sesion_cliente.html'

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return render(request, 'Dashboard_Cliente.html')
        else:
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active and not user.is_staff:
                    login(request, user)
                    request.session['id_carro'] = obtener_id_carro(request)

apps/website/templates/cambiar_password.html
{% extends 'inicio_sesion_cliente.html' %}

{% block center %}

{% if validlink %}

<p>Nueva contraseña</p>

<form method="post" style="width:30%;margin: auto;">
{% csrf_token %}

{{ form.new_password1.errors }}
<label for="id_new_password1">Nueva contraseña:</label>
{{ form.new_password1 }}

{{ form.new_password2.errors }}
<label for="id_new_password2">Confirme la contraseña:</label>{{ form.new_password2 }}
<input type="submit" class="button_2" style="margin-top: 10px;" value="Guardar" />
</form>

{% else %}

<h1 class="text-center">ENLACE INVÁLIDO: ESTE ENLACE YA HA SIDO UTILIZADO</h1>

{% endif %}

{% endblock %}

apps/website/templates/confirmacion_olvido_password.html
{% extends 'inicio_sesion_cliente.html' %}

{% block center %}

<h4>Te hemos enviado un correo con un enlace para reestablecer tu contraseña</h4>

{% endblock %}

apps/website/templates/correo_cambio.html
Solicitaste reestablecimiento de contraseña.
Click en el siguiente link para crear una nueva contraseña.
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Tu nombre de usuario es: {{ user.get_username }}
 

apps/website/templates/inicio_sesion_cliente.html
{% extends 'home.html' %}
{% load staticfiles %}
{% block css%}
<style type="text/css">
    .titulo {
        margin: 0 auto;
        text-align: center;

        font-family: AzoSansBold;
        font-size: 14pt;
        width: 98%;
        margin-top: 50px;
    }

    .form-estilo {

        margin: 30px auto;
        width: 83%;
    }

    .inpu {
        float: left;
        width: 230px;
        position: relative;
        margin-right: 10px;
        left: 23px;
        top: 0px;
        width: 250px;
        height: 33px;
        border: 1px solid #999;
    }

    .link {
        float: left;
        position: relative;
        top: 7px;
    }

    .col-sm-12,
    .col-lg-12 {
        padding: 0 !important;
    }

    

    .caja {
        width: 250px !important;
    }


    @media screen and (max-width: 568px)and (min-width: 568px) {
        .fondo {
            background: url('{% static 'images/website/VerMovil568.png' %}') no-repeat !important;
            height: 501px;
            max-width: 100%;
        }
        .form-estilo {
            width: 82%;
            margin: 0 auto;
        }
        .caja {
            width: 200px !important;
        }
    }

    @media screen and (max-width: 384px),
    (max-width: 360px),
    (max-width: 375px) {
        .fondo {
            background: url('{% static 'images/website/VerMovil3.png' %}') no-repeat !important;
            height: 335px;
            max-width: 100%;
        }
        .form-estilo {
            width: 82%;
            margin: 0 auto;
        }
        .caja {
            width: 200px !important;
        }
        .subtitulo {
            margin-top: 8px !important;
            font-size: 10pt !important;
        }
        .titulo {
            font-size: 11pt !important;
        }
    }

    @media screen and (max-width: 320px) {
        .fondo {
            content: url('{% static 'images/website/VerMovil320.png' %}');
            max-width: 100%;
        }
        .caja {
            width: 160px !important;
        }
        .subtitulo {
            margin-top: 8px !important;
            font-size: 11pt !important;
        }
        .btn {
            font-size: 7pt;
        }
        .olvido {
            font-size: 10pt!important;
            margin-top: 60px !important;
        }
    }

    @media screen and (min-width:533px)and (max-width:533px) {
        .fondo {
            content: url('{% static 'images/website/VerMovil533.png' %}');
           
            height: 470px;
            max-width: 100%;
        }
        .form-estilo {
            margin: 0 auto;
            width: 62%;
        }
        .caja {
            width: 230px !important;
        }
        .subtitulo {
            margin-top: 15px !important;
            font-size: 11pt !important;
        }
    }

    .subtitulo {
        margin: 25px auto;
        font-size: 15pt;
    }

    .olvido {
        font-size: 11pt;
        width: 100%;
        margin-top: 76px;
    }
</style>
{% endblock css%}
{% block content %}
<img class="fondo" src="{% static 'images/website/FONDO_VIMANuevo.png' %}" style="max-width: 100%;position: absolute;width: 1349px;height: 319px;" />
<div class="row ">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3"><label class="titulo">BIENVENIDO A VIMA MODA</label></div>
            <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                <form id="inicio_cliente" class="form-estilo" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}">
                    <div class="input-group" style="margin: 0 auto;margin-bottom: 10px;">
                        <div style="background: url('{% static 'images/website/icono-1-registro2.png' %}') no-repeat; border: 1px solid #999;border-radius: 4px 0px 0px 4px;width: 41px; height: 33px;float: left;z-index: 100;position: relative;left: 27px;border-right: none;top: 0px;"></div>
                        <input class="inpu form-control caja" type="text" name="username" required="required" placeholder="Nombre de usuario" />
                    </div>
                    <div class="input-group" style="margin: 0 auto;margin-bottom: 10px;">
                        <div style="background: url('{% static 'images/website/icono-4registro2.png' %}') no-repeat; border: 1px solid #999;border-radius: 4px 0px 0px 4px;width: 41px; height: 33px;float: left;z-index: 100;position: relative;left: 28px;border-right: none;"></div>
                        <input class="inpu form-control caja" type="password" id="password" name="password" required="required" placeholder="">
                    </div>
                    <div>
                        <a class="link" href="{% url 'website:forgot_password' %}" style="font-family: AzoSansBold;">¿Olvidó la contraseña?</a>
                    </div>
                    <div style="float: right;">
                        <div style="float: right;margin-top: 4px;">
                            <input type="checkbox" id="recuerda"><label for="recuerda" style="margin-top: 3px;font-family: AzoSansBold;margin-left: 6px;">Recuerdame</label>
                        </div>
                    </div>
                    <div class="col-sm-4 col-lg-4 col-xs-offset-4 input-group">
                        <input class="btn btn-primary" type="submit" value="INICIAR SESIÓN" id="btn_ingresar" style="margin-top: 30px;">
                    </div>
                </form>
            </div>
            <div class="col-sm-4 col-lg-4 col-md-offset-4">
                <div class="input-group subtitulo" style="text-align: center;margin: 0 auto;font-size: 18px;font-family: AzoSansBold;">
                    <label style="float: left;">¿No estás registrado aún?</label>
                    <label style="float: left;margin-left: 10px;">
                        <a style="float: left;" href="{% url 'website:registro_cliente' %}">Registrate aquí</a>
                    </label>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
{% endblock %}

apps/website/templates/inicio_sesion_designer_lounge.html
{% extends 'home.html' %} {% load staticfiles %} {% block css%}
<style type="text/css">
    .titulo {
        margin: 0 auto;
        text-align: center;

        font-family: AzoSansBold;
        font-size: 14pt;
        width: 98%;
        margin-top: 50px;
    }

    .form-estilo {

        margin: 30px auto;
        width: 83%;
    }

    .inpu {
        float: left;
        width: 230px;
        position: relative;
        margin-right: 10px;
        left: 23px;
        top: 0px;
        width: 250px;
        height: 33px;
        border: 1px solid #999;
    }

    .link {
        float: left;
        position: relative;
        top: 7px;
    }

    .col-sm-12,
    .col-lg-12 {
        padding: 0 !important;
    }

    

    .caja {
        width: 250px !important;
    }


    @media screen and (max-width: 568px)and (min-width: 568px) {
        .fondo {
            background: url('{% static 'images/website/VerMovil568.png' %}') no-repeat !important;
            height: 501px;
            max-width: 100%;
        }
        .form-estilo {
            width: 82%;
            margin: 0 auto;
        }
        .caja {
            width: 200px !important;
        }
    }

    @media screen and (max-width: 384px),
    (max-width: 360px),
    (max-width: 375px) {
        .fondo {
            background: url('{% static 'images/website/VerMovil3.png' %}') no-repeat !important;
            height: 335px;
            max-width: 100%;
        }
        .form-estilo {
            width: 82%;
            margin: 0 auto;
        }
        .caja {
            width: 200px !important;
        }
        .subtitulo {
            margin-top: 8px !important;
            font-size: 10pt !important;
        }
        .titulo {
            font-size: 11pt !important;
        }
    }

    @media screen and (max-width: 320px) {
        .fondo {
            content: url('{% static 'images/website/VerMovil320.png' %}');
            max-width: 100%;
        }
        .caja {
            width: 160px !important;
        }
        .subtitulo {
            margin-top: 8px !important;
            font-size: 11pt !important;
        }
        .btn {
            font-size: 7pt;
        }
        .olvido {
            font-size: 10pt!important;
            margin-top: 60px !important;
        }
    }

    @media screen and (min-width:533px)and (max-width:533px) {
        .fondo {
            content: url('{% static 'images/website/VerMovil533.png' %}');
           
            height: 470px;
            max-width: 100%;
        }
        .form-estilo {
            margin: 0 auto;
            width: 62%;
        }
        .caja {
            width: 230px !important;
        }
        .subtitulo {
            margin-top: 15px !important;
            font-size: 11pt !important;
        }
    }

    .subtitulo {
        margin: 25px auto;
        font-size: 15pt;
    }

    .olvido {
        font-size: 11pt;
        width: 100%;
        margin-top: 76px;
    }
</style>
{% endblock css%} {% block content %}
<img class="fondo" src="{% static 'images/website/FONDO_VIMANuevo.png' %}" style="max-width: 100%;position: absolute;width: 1349px;height: 319px;" />
<div class="row ">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3"><label class="titulo">BIENVENIDO A VIMA MODA</label></div>
            <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                <form id="iniciar_designer" class="form-estilo" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}">
                    <div class="input-group" style="margin: 0 auto;margin-bottom: 10px;">
                        <div style="background: url('{% static 'images/website/icono-1-registro2.png' %}') no-repeat; border: 1px solid #999;border-radius: 4px 0px 0px 4px;width: 41px; height: 33px;float: left;z-index: 100;position: relative;left: 27px;border-right: none;top: 0px;"></div>
                        <input class="inpu form-control caja" type="text" name="username" required="required" placeholder="Nombre de usuario" />
                    </div>
                    <div class="input-group" style="margin: 0 auto;margin-bottom: 10px;">
                        <div style="background: url('{% static 'images/website/icono-4registro2.png' %}') no-repeat; border: 1px solid #999;border-radius: 4px 0px 0px 4px;width: 41px; height: 33px;float: left;z-index: 100;position: relative;left: 28px;border-right: none;"></div>
                        <input class="inpu form-control caja" type="password" id="password" name="password" required="required" placeholder="">
                    </div>
                    <div>
                        <a class="link" href="{% url 'website:forgot_password' %}" style="font-family: AzoSansBold;">¿Olvidó la contraseña?</a>
                    </div>
                    <div style="float: right;">
                        <div style="float: right;margin-top: 4px;">
                            <input type="checkbox" id="recuerda"><label for="recuerda" style="margin-top: 3px;font-family: AzoSansBold;margin-left: 6px;">Recuerdame</label>
                        </div>
                    </div>
                    <div class="col-sm-4 col-lg-4 col-xs-offset-4 input-group">
                        <input class="btn btn-primary" type="submit" value="INICIAR SESIÓN" id="btn_ingresar" style="margin-top: 30px;">
                    </div>
                </form>
            </div>
            <div class="col-sm-4 col-lg-4 col-md-offset-4">
                <div class="input-group subtitulo" style="text-align: center;margin: 0 auto;font-size: 18px;font-family: AzoSansBold;">
                    <label style="float: left;">¿No estás registrado aún?</label>
                    <label style="float: left;margin-left: 10px;">
                        <a style="float: left;" href="{% url 'website:designer_lounge_registro' %}">Registrate aquí</a>
                    </label>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
{% endblock %}

apps/website/templates/listado.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
listado
</body>
</html>