apps/compras/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # URLs de Ordenes de compra
    url(r'^orden/search/$', search, name='search'),
    url(r'^orden/registro/$', login_required(Ordenes_Crear),name='ordenes_crear'),
    url(r'^orden/listado', login_required(Ordenes_Listado.as_view()),
        name='ordenes_listado'),
    url(r'^orden/anular/(?P<id_compra>\d+)/$',
        login_required(Orden_Anular), name='ordenes_anular'),
    url(r'^orden/modificar/(?P<id_compra>\d+)/$',
        login_required(Orden_modificar), name='ordenes_modificar'),
    url(r'^orden/previsualizar/$',
        login_required(Orden_Previsualizar), name='ordenes_previsualizar'),
    url(r'^orden/imprimir/(?P<id_compra>\d+)/', login_required(mostrar_pdf),
        name='ordenes_imprimir'),
    url(r'^orden/descargar/(?P<id_compra>\d+)/', login_required(descargar_pdf),
        name='ordenes_descargar'),
    url(r'^orden/correo/$', login_required(enviar_correo),
        name='ordenes_descargar'),
    # URLs de Recepciones de compra
    url(r'^recepcion/registro/$', login_required(Recepcion_Crear),name='recepcion_crear'),
    url(r'^recepcion/listado', login_required(Recepcion_Listado.as_view()),
        name='recepcion_listado'),
    url(r'^recepcion/anular/(?P<id_recepcion>\d+)/$',
        login_required(Recepcion_Anular), name='recepcion_anular'),
    url(r'^recepcion/detalle/$',
        login_required(Recepcion_Detalle), name='recepcion_detalle'),
    url(r'^recepcion/mostrar/$',
        login_required(Recepcion_Mostrar), name='recepcion_mostrar'),
]

apps/cuentas_pagar/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.cuentas_pagar.views import ProveedorListar, ProveedorCrear, ProveedorModificar, ProveedorEliminar,\
 ProveedoresDebtListar, CuentasPagarCrear, CuentasPagarListar, VistaPagosAjax, mostrar_pdf, mostrar_pdf_prov

urlpatterns = [
    url(r'^proveedor$',login_required(ProveedorListar.as_view()), name='listar_proveedores'),
    url(r'^proveedor/nuevo$', login_required(ProveedorCrear.as_view()), name='crear_proveedores'),
    url(r'^proveedor/editar/(?P<pk>\d+)$',login_required(ProveedorModificar.as_view()), name='editar_proveedores'),
    url(r'^proveedor/borrar/(?P<pk>\d+)$',login_required(ProveedorEliminar.as_view()), name='eliminar_proveedores'),
    url(r'^estado_cuenta/$',login_required(ProveedoresDebtListar.as_view()), name='listar_cuentas_pagar'),    
    url(r'^estado_cuenta/get_debt_proveedor/(?P<pk>\d+)$$',login_required(CuentasPagarListar.as_view()), name='buscar_deuda_proveedor'),      
    url(r'^estado_cuenta/settle_debt_proveedor/(?P<id_cuenta_pagar>\d+)$',login_required(VistaPagosAjax.as_view()), name='cancelar_deuda_proveedor'),
    url(r'^facturar/(?P<id_recepcion>\d+)/$', 
        login_required(CuentasPagarCrear.as_view()), name='recepcion_facturar'),
    url(r'^proveedor/listar/(?P<estado>\d+)/$', login_required(mostrar_pdf),
        name='listado_proveedores'),
    url(r'^estado_cuenta/mostrar/(?P<prov>\d+)/$', login_required(mostrar_pdf_prov),
        name='mostrar_estado_cuenta'),
]

vima/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from apps.administrador.views import cerrar_sesion
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    # url(r'^admin/', admin.site.urls), no se usara el admin de django
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'clave_formulario.html',
        'email_template_name': 'clave_correo.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'clave_enviado.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'clave_confirmar.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'clave_cambiada.html'},
        name='password_reset_complete'),


    url(r'^administrador/', include('apps.administrador.urls', namespace='administrador')),
    url(r'^inventario/', include('apps.inventario.urls', namespace='inventario')),
    url(r'^compras/', include('apps.compras.urls', namespace='compras')),
    url(r'^cuentas_pagar/', include('apps.cuentas_pagar.urls', namespace='cuentas_pagar')),
    url(r'^cerrar_sesion/$', cerrar_sesion, name='cerrar_sesion'),

    url(r'^', include('apps.website.urls', namespace='website'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/compras/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from apps.cuentas_pagar.models import Proveedores
from apps.inventario.models import Productos, Almacenes
from apps.website.models import Ventas

class OrdenesCompras(models.Model):
    id_compra = models.AutoField(primary_key=True)
    fecha_registro = models.DateField(
        auto_now_add=True, editable=True, verbose_name=_('Fecha de la Orden'))
    observaciones = models.CharField(
        max_length=300, null=True, blank=True, verbose_name=_('Observaciones'))
    monto_total = models.DecimalField(
        null=True, blank=True, max_digits=19, decimal_places=3,
                                default=0.0, verbose_name=_('monto de la orden'))
    id_usuario = models.ForeignKey(
        User, null=True, blank=True, verbose_name=_('Usuario que Registra la Orden'))
    estado = models.CharField(
        max_length=10, null=False, blank=False, verbose_name=_('Estado de la Orden'))
    id_almacen = models.ForeignKey(
        Almacenes, null=False, blank=False, default=0, verbose_name=_('Almacén que recibirá la Mercancía'))
    id_proveedor = models.ForeignKey(
        Proveedores, null=False, blank=False, default=0, verbose_name=_('Proveedor Relacionado'))

    class Meta:
        db_table = 'orden_compra'
        verbose_name = 'Orden de Compra'
        verbose_name_plural = 'Ordenes de Compras'

    def __str__(self):
        return 'Orden #{} - Proveedor:{}'.format(self.id_compra,self.id_proveedor)


class DetalleOrdenCompra(models.Model):
    id_detalle = models.AutoField(primary_key=True)
    id_compra = models.ForeignKey(
        OrdenesCompras, null=True, blank=True, verbose_name=_('Orden de Compra Asociada'))
    id_producto = models.ForeignKey(
        Productos, null=True, blank=True, verbose_name=_('producto'))
    talla = models.CharField(
        max_length=20, null=False, blank=True, verbose_name=_('Talla'))
    nombre_color = models.CharField(
        max_length=100, null=False, blank=True, verbose_name=_('nombre del color'))
    color = models.CharField(
        max_length=10, null=False, blank=True, verbose_name=_('color'))
    cantidad = models.IntegerField(null=True, blank=True,verbose_name=_('cantidad requerida'))
    cantidad_recibida = models.IntegerField(default=0,
                                            verbose_name=_('cantidad recibida'))
    precio = models.DecimalField(null=True, blank=True, max_digits=19, decimal_places=3,
                                 default=0.0, verbose_name=_('Precio del Producto'))
    porcentaje_ganancia = models.IntegerField(
        null=False, default = 0, verbose_name=_('porcentaje de ganancia'))
    total = models.DecimalField(null=True, blank=True, max_digits=19, decimal_places=3,
                                default=0.0, verbose_name=_('Total'))

    class Meta:
        unique_together = (("id_compra", "id_producto", "talla", "color"),)
        db_table = 'detalle_orden_compra'
        verbose_name = 'Detalle de Orden de Compra'
        verbose_name_plural = 'Detalles de Ordenes de Compras'



class RecepcionCompras(models.Model):
    id_recepcion = models.AutoField(primary_key=True)
    id_orden_compra = models.ForeignKey(
        OrdenesCompras, null=True, blank=True, verbose_name=_('Orden de Compra Asociada'))
    fecha_registro = models.DateField(
        auto_now_add=True, editable=True, verbose_name=_('Fecha de Registro'))
    fecha_recepcion = models.DateField(verbose_name=_('Fecha de Recepción'))
    observaciones = models.CharField(
        max_length=300, null=False, blank=False, verbose_name=_('Observaciones'))
    monto = models.DecimalField(max_digits=19, decimal_places=3,
                                default=0.0, verbose_name=_('Monto de la Recepción'))
    impuesto = models.DecimalField(max_digits=19, decimal_places=3,
                                   default=0.0, verbose_name=_('Monto de Impuesto'))
    porcentaje_impuesto = models.IntegerField(default=12, verbose_name=_('Porcentaje de Impuesto'))
    monto_flete = models.DecimalField(max_digits=19, decimal_places=3,
                                      default=0.0, verbose_name=_('Monto por Flete'))
    porcentaje_flete = models.IntegerField(default=10,verbose_name=_('Porcentaje por Flete'))
    id_usuario = models.ForeignKey(
        User, null=True, blank=True, verbose_name=_('Usuario que Recibe la Mercancía'))
    estado = models.CharField(
        max_length=10, null=False, blank=False, verbose_name=_('Estado de la Recepción'))

    class Meta:
        db_table = 'recepcion_compra'
        verbose_name = 'Recepción de Compra'
        verbose_name_plural = 'Recepciones de Compras'


class DetalleRecepcionCompra(models.Model):
    id_detalle = models.AutoField(primary_key=True)
    id_producto = models.ForeignKey(
        Productos, null=True, blank=True, verbose_name=_('Producto'))
    id_recepcion = models.ForeignKey(
        RecepcionCompras, null=True, blank=True, verbose_name=_('Recepción de Compra Asociada'))
    talla = models.CharField(
        max_length=20, null=False, blank=True, verbose_name=_('Talla'))
    nombre_color = models.CharField(
        max_length=100, null=False, blank=True, verbose_name=_('nombre del Color'))
    color = models.CharField(
        max_length=10, null=False, blank=True, verbose_name=_('Color'))
    id_lote = models.IntegerField(
        null=False, verbose_name=_('Identificador del Lote'))
    cantidad = models.IntegerField(verbose_name=_('Cantidad Requerida'))
    cantidad_recibida = models.IntegerField(verbose_name=_('Cantidad Recibida'))
    precio = models.DecimalField(max_digits=19, decimal_places=3,
                                 default=0.0, verbose_name=_('Precio del Producto'))
    total = models.DecimalField(max_digits=19, decimal_places=3,
                                default=0.0, verbose_name=_('Total'))

    class Meta:
        db_table = 'detalle_recepcion_compra'
        verbose_name = 'Detalle de Recepción de Compra'
        verbose_name_plural = 'Detalles de Recepciones de Compras'

    

apps/compras/forms.py
from django import forms
from apps.compras.models import OrdenesCompras, RecepcionCompras,Proveedores,Almacenes
from django.core.exceptions import ValidationError
from django.db.models import Q


class OrdenesForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['id_proveedor'].widget.attrs.update({'class': 'selectpicker', 'data-live-search': 'true', 'data-width': '98%', 'required': 'required', 'title': 'Proveedores', })
        self.fields['id_almacen'].widget.attrs.update({'class': 'selectpicker', 'data-live-search': 'true', 'data-width': '98%', 'title': 'Almacen', 'required': 'required', })
    caracteristicas = forms.HiddenInput()
    id_proveedor = forms.ModelChoiceField(queryset=Proveedores.objects.filter(activo=True))
    id_almacen = forms.ModelChoiceField(queryset=Almacenes.objects.filter(activo=True))
    caracteristicas = forms.HiddenInput()
    class Meta:
        model = OrdenesCompras
        fields = ['observaciones', 'id_almacen',
                  'id_proveedor', 'id_usuario', 'estado']
        widgets = {
            'observaciones': forms.Textarea(attrs={'class': 'form-control ', 'rows': 8, 'cols': 200, 'style': 'resize:none;'}),
            'fecha_registro': forms.HiddenInput(),
            'id_usuario': forms.HiddenInput(),
            'estado': forms.HiddenInput(),
        }


class RecepcionForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['id_orden_compra'].widget.attrs.update({'class': 'selectpicker', 'data-live-search': 'true', 'data-width': '70%', 'required': 'required', 'title': 'Orden de Compra', 'style': 'float:left;'})
    caracteristicas = forms.HiddenInput()
    id_orden_compra = forms.ModelChoiceField(queryset=OrdenesCompras.objects.filter(Q(estado="Enviada") | Q(estado= "Parcial")))
    class Meta:
        model = RecepcionCompras
        fields = ['id_orden_compra','fecha_recepcion','observaciones', 'monto', 'porcentaje_impuesto',
                  'impuesto', 'porcentaje_flete', 'monto_flete', 'estado']
        widgets = {
            'fecha_recepcion': forms.DateInput(attrs={'class':'form-control datepicker','date-date-format': 'YYYY-MM-DD', 'style':'    width: 100%', 'required': True}),
            'observaciones': forms.Textarea(attrs={'class': 'form-control ', 'rows': 4, 'cols': 300, 'style': 'resize:none;padding-top:14px'}),
            'monto': forms.TextInput(attrs={'onKeyPress':'return soloNumeros(event);','style':'width:100%'}),
            'porcentaje_impuesto': forms.NumberInput(attrs={'minlength': 1, 'maxlength': 100, 'required': True, 'type': 'number','style':'    width: 100%', 'onKeyPress':'return soloNumeros(event);','onfocusout':'calculoImpuesto();'}),
            'impuesto': forms.TextInput(attrs={'style':'    width: 100%', 'onKeyPress':'return soloNumeros(event);'}),
            'porcentaje_flete': forms.NumberInput(attrs={'minlength': 1, 'maxlength': 100, 'required': True, 'type': 'number','style':'    width: 100%', 'onKeyPress':'return soloNumeros(event);','onfocusout':'calculoFlete();'}),
            'monto_flete': forms.TextInput(attrs={'style':'    width: 103%', 'onKeyPress':'return soloNumeros(event);'}),
            'fecha_registro': forms.HiddenInput(),
            'id_usuario': forms.HiddenInput(),
            'estado': forms.HiddenInput(),
        }

apps/compras/templates/modales.html
{% extends 'base.html' %}
{% block modales %}
<div id="prueba" class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      ...
    </div>
  </div>
</div>
{% endblock %}

apps/compras/templates/ordenes_anular.html
{% extends 'base.html' %}

{% block contenido %}
<div class="panel panel-primary" style="position: relative; top: 10px;">
  <div class="panel-heading">Confirmar Anulación</div>
	<form method="post" style="text-align: center;">
		{% csrf_token %}
		<div class="alert alert-warning" style="width: 50%;margin: auto;margin-top: 14px;">
			<h4>¿Está seguro de Anular la Orden #{{ orden.id_compra }}?</h4>
			<button class="btn btn-primary" type="submit">Si</button>
			<a class="btn btn-default" href="{% url 'compras:ordenes_listado' %}">No</a>
		</div>
	</form>
</div>
{% endblock %}

apps/compras/templates/ordenes_listar.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block css%}

<style>
.form-control{
        bottom: 4px !important;
        position: relative !important;
        height: 30px !important;
    }
.btn-default, .btn-default:hover, .btn-default:focus, .btn-default:active, .btn-default.active, .open > .dropdown-toggle.btn-default, .btn-default.disabled, .btn-default[disabled], fieldset[disabled] .btn-default, .btn-default.disabled:hover, .btn-default[disabled]:hover, fieldset[disabled] .btn-default:hover, .btn-default.disabled:focus, .btn-default[disabled]:focus, fieldset[disabled] .btn-default:focus, .btn-default.disabled:active, .btn-default[disabled]:active, fieldset[disabled] .btn-default:active, .btn-default.disabled.active, .btn-default.active[disabled], fieldset[disabled] .btn-default.active{
    background-color: #e9ecf2;
    border-color: #e9ecf2;
    color: #1b3548;
}
</style>
{% endblock css%}

{% block contenido %}

<div class="panel panel-primary panel-vima">
    <div class="panel-heading">Listado de Ordenes de Compra</div>

    <a class="glyphicon glyphicon-plus btn-nuevo " href="{% url 'compras:ordenes_crear' %}">Nuevo</a>

    <div class="table-responsive">
        <table class="table table-hover">
        {% if object_list %}
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Proveedor</td>
                    <td>Monto</td>
                    <td>Almacen</td>
                    <td>Creado por</td>
                    <td>Estado</td>
                    <td style="text-align: center">Opciones</td>
                </tr>
            </thead>
            <tbody>
                {% for orden in object_list %}
                <tr>
                    <td>{{ orden.id_compra }}</td>
                    <td>{{ orden.id_proveedor.nombre_empresa }}</td>
                    <td>{{ orden.monto_total|floatformat:"2" }}</td>
                    <td>{{ orden.id_almacen.descripcion }}</td>
                    <td>{{ orden.id_usuario.first_name }} {{ orden.id_usuario.last_name }}</td>
                    <td>{{ orden.estado }}</td>
                    <td style="text-align: center">
                    {% ifequal orden.estado 'Sin Enviar' %}
                            <a class="glyphicon glyphicon-pencil" href="{% url 'compras:ordenes_modificar' orden.id_compra %}" title="Modificar"/>
                    {% endifequal %}
                    {% if orden.estado == 'Enviada' or orden.estado == 'Sin Enviar' %}
                            <a class="glyphicon glyphicon-remove" href="{% url 'compras:ordenes_anular' orden.id_compra %}" title="Anular"/>
                    {% endif %}
                    {% if orden.estado != 'Anulada' and orden.estado != 'Sin Enviar' %}
                            <a class="glyphicon glyphicon-print" href="{% url 'compras:ordenes_imprimir' orden.id_compra %}" title="Mostrar" />
                    {% endif %}
                    </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
            {% if is_paginated %}
                <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in page_obj.paginator.page_range %}
                          {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                          {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                          {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                </ul>
            {% endif %}
    {% else %}
        <h3 style="text-align: center;">No Hay Registros de ordenes.</h3>
    {% endif %}
</div>


{% endblock %}
{% block js %}
    <script src="{% static 'js/bootstrap-table.js' %}"></script>
{% endblock %}

apps/compras/templates/recepcion_anular.html
{% extends 'base.html' %}

{% block contenido %}
<div class="panel panel-primary" style="position: relative; top: 10px;">
  <div class="panel-heading">Confirmar Anulación</div>
	<form method="post" style="text-align: center;">
		{% csrf_token %}
		<div class="alert alert-warning" style="width: 50%;margin: auto;margin-top: 14px;">
			<h4>¿Está seguro de Anular la Recepción #{{ recepcion.id_recepcion }}?</h4>
			<button class="btn btn-primary" type="submit">Si</button>
			<a class="btn btn-default" href="{% url 'compras:recepcion_listado' %}">No</a>
		</div>
	</form>
</div>
{% endblock %}

apps/compras/templates/recepcion_facturar.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block css%}

<style type="text/css">
    .btn-group{
        width: 600px;
    }

</style>
{% endblock css%}
{% block contenido %}
<div class="panel panel-primary panel-vima">
    <div class="panel-heading">Registro de Factura</div>
        {% if recepcion.id_orden_compra.estado == "Parcial" %}
                    <h4 class="alert alert-warning"><b>La Recepcion de Mercancía se guardó satisfactoriamente,</b> puede registrar la factura ahora y cerrar la orden de compra con productos faltantes, o registrarla en una proxima recepción presionando el botón <b>"Volver"</b> </h4>
        {% endif %}

        {% if recepcion.id_orden_compra.estado == "Procesada" %}
                    <h4 class="alert alert-warning"><b>La Recepcion de Mercancía se guardó satisfactoriamente,</b> debe registrar la factura relacionada para generar la cuenta por pagar, y completar el proceso.</b> </h4>
        {% endif %}

            <label style="font-size: 18px;padding:10px;padding-left:16px;">
                <b>Proveedor de la Cuenta:</b> {{recepcion.id_orden_compra.id_proveedor.id_proveedor}} - {{recepcion.id_orden_compra.id_proveedor.nombre_empresa}}
            </label>
            <input type="hidden" id="sub" name="sub" value="{{sub}}">
    <form id="form_cuenta_pagar" method="post" enctype="multipart/form-data" action="/cuentas_pagar/facturar/{{recepcion.id_recepcion}}/">
        {% csrf_token %}
            <input type="hidden" id="id_id_proveedor" name="id_proveedor" value="{{ recepcion.id_orden_compra.id_proveedor.id_proveedor }}">
            <input type="hidden" id="tipo_transaccion" name="tipo_transaccion" value="FAC">
            <input type="hidden" id="id_id_recepcion" name="id_recepcion" value="{{ recepcion.id_recepcion }}">
            <input type="hidden" id="id_id_usuario" name="id_usuario" value="{{ user.id }}">
            <input type="hidden" id="estado" name="estado" value="Pendiente">
            <div class='row'>
                <div class='col-sm-3'>    
                    <div class='form-group'>
                        <label for="{{form.numero_documento.name}}">Numero de Documento:</label>
                        {{form.numero_documento}}
                    </div>
                </div>
                <div class='col-sm-3'>
                    <div class='form-group'>
                        <label for="{{form.numero_control.name}}">Numero de Control:</label>
                        {{form.numero_control}}
                    </div>
                </div>
                <div class='col-sm-3'>
                    <div class='form-group'>
                        <label for="{{form.fecha_documento.name}}">Fecha del Documento:</label>
                        {{form.fecha_documento}}
                    </div>
                </div>
                <div class='col-sm-3'>
                    <div class='form-group'>
                        <label for="{{form.fecha_vencimiento.name}}">Fecha de Vencimiento:</label>
                        {{form.fecha_vencimiento}}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class='col-sm-12'>
                    <div class="form-group">
                        <label for="{{form.concepto.name}}">Concepto:</label>
                        {{form.concepto}}
                    </div>
                </div>
            </div>
            <div class='row'>
                <div class='col-sm-4'>    
                    <div class='form-group'>
                        <label for="{{form.subtotal.name}}">Sub-Total:</label>
                        {{form.subtotal}}
                    </div>
                </div>
                <div class='col-sm-4'>
                    <div class='form-group'>
                        <label for="{{form.porcentaje_impuesto.name}}">% Impuesto:</label>
                        {{form.porcentaje_impuesto}}
                    </div>
                </div>
                <div class='col-sm-4'>
                    <div class='form-group'>
                        <label for="{{form.impuesto.name}}">Monto del Impuesto:</label>
                        {{form.impuesto }}
                    </div>
                </div>
            </div>
            <div class='row'>
                <div class='col-sm-4'>    
                    <div class='form-group'>
                        <label for="{{form.porcentaje_flete.name}}">% Flete:</label>
                        {{form.porcentaje_flete}}
                    </div>
                </div>
                <div class='col-sm-4'>
                    <div class='form-group'>
                        <label for="{{form.monto_flete.name}}">Monto de Flete:</label>
                        {{form.monto_flete }}
                    </div>
                </div>
                <div class='col-sm-4'>
                    <div class='form-group'>
                        <label for="{{form.monto.name}}">Monto Total a Pagar:</label>
                        {{form.monto}}
                    </div>
                </div>
            </div>

            <div class="center-bottom">
                <input id="procesar_orden" class="btn btn-primary" type="submit" value="Guardar">
                {% if recepcion.id_orden_compra.estado == "Parcial" %}
                    <a class="btn btn-default" href="/compras/recepcion/listado/">Volver</a>
                {% endif %}
            </div>
    </div>

</form>

{% endblock contenido %}

{% block js %}
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript">
$(function (){
        $(function () {
            $(document).ready(function () {
                $('#id_subtotal').val($('#sub').val().replace(",","."));
                $('#id_monto').val($('#sub').val().replace(",","."));
        });
        $('#id_fecha_documento').datepicker({
            inline: true,
            sideBySide: true,
            format: 'yyyy-mm-dd'
        });

        $('#id_fecha_vencimiento').datepicker({
            inline: true,
            sideBySide: true,
            format: 'yyyy-mm-dd'
        });
    });
});

function validarCampos() {
     var orden = $('#id_id_orden_compra').val();
     var fecha = $('#id_fecha_recepcion').val();
     var monto = $('#id_monto').val();
     var porcentajei = $('#id_porcentaje_impuesto').val();
     var impuesto = $('#id_impuesto').val();
     var porcentajef = $('#id_porcentaje_flete').val();
     var flete = $('#id_monto_flete').val();
    if(orden == "" || fecha == "" || monto  == "" || porcentajei == "" || impuesto == ""){
        mostrarMensajes("Por favor complete todos los campos obligatorios.");
        return false;
    }else{
        return true;
    }
}

function calculoImpuesto() {
    var porc=$('#id_porcentaje_impuesto').val();
    var mont=$('#id_subtotal').val(); 
    var cal=mont*(porc/100);
    $('#id_impuesto').val(cal.toFixed(2));
}
   
function calculoflete() {
    var porc=$('#id_porcentaje_flete').val();
    var mont=$('#id_subtotal').val();
    var cal=mont*(porc/100);
    $('#id_monto_flete').val(cal.toFixed(2));
} 

function calculoTotal() {
    var imp=$('#id_impuesto').val();
    var fle=$('#id_monto_flete').val();
    var mont=$('#id_subtotal').val();
    var cal = parseFloat(mont) + parseFloat(imp) + parseFloat(fle);
    $('#id_monto').val(cal.toFixed(2))
} 
</script>
{% endblock js %}