apps/cuentas_pagar/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.cuentas_pagar.views import ProveedorListar, ProveedorCrear, ProveedorModificar, ProveedorEliminar,\
 ProveedoresDebtListar, CuentasPagarCrear, CuentasPagarListar, VistaPagosAjax, mostrar_pdf, mostrar_pdf_prov

urlpatterns = [
    url(r'^proveedor$',login_required(ProveedorListar.as_view()), name='listar_proveedores'),
    url(r'^proveedor/nuevo$', login_required(ProveedorCrear.as_view()), name='crear_proveedores'),
    url(r'^proveedor/editar/(?P<pk>\d+)$',login_required(ProveedorModificar.as_view()), name='editar_proveedores'),
    url(r'^proveedor/borrar/(?P<pk>\d+)$',login_required(ProveedorEliminar.as_view()), name='eliminar_proveedores'),
    url(r'^estado_cuenta/$',login_required(ProveedoresDebtListar.as_view()), name='listar_cuentas_pagar'),    
    url(r'^estado_cuenta/get_debt_proveedor/(?P<pk>\d+)$$',login_required(CuentasPagarListar.as_view()), name='buscar_deuda_proveedor'),      
    url(r'^estado_cuenta/settle_debt_proveedor/(?P<id_cuenta_pagar>\d+)$',login_required(VistaPagosAjax.as_view()), name='cancelar_deuda_proveedor'),
    url(r'^facturar/(?P<id_recepcion>\d+)/$', 
        login_required(CuentasPagarCrear.as_view()), name='recepcion_facturar'),
    url(r'^proveedor/listar/(?P<estado>\d+)/$', login_required(mostrar_pdf),
        name='listado_proveedores'),
    url(r'^estado_cuenta/mostrar/(?P<prov>\d+)/$', login_required(mostrar_pdf_prov),
        name='mostrar_estado_cuenta'),
]

vima/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from apps.administrador.views import cerrar_sesion
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    # url(r'^admin/', admin.site.urls), no se usara el admin de django
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'clave_formulario.html',
        'email_template_name': 'clave_correo.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'clave_enviado.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'clave_confirmar.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'clave_cambiada.html'},
        name='password_reset_complete'),


    url(r'^administrador/', include('apps.administrador.urls', namespace='administrador')),
    url(r'^inventario/', include('apps.inventario.urls', namespace='inventario')),
    url(r'^compras/', include('apps.compras.urls', namespace='compras')),
    url(r'^cuentas_pagar/', include('apps.cuentas_pagar.urls', namespace='cuentas_pagar')),
    url(r'^cerrar_sesion/$', cerrar_sesion, name='cerrar_sesion'),

    url(r'^', include('apps.website.urls', namespace='website'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cuentas_pagar/models.py
""" Modelos de la app cuentas_pagar """
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core import validators
from django.conf import settings
from django.contrib.auth.models import User


class Paises(models.Model):
    """
        Modelo para lista de países.
    """
    id_pais = models.CharField(
        primary_key=True,
        max_length=3,
        blank=False,
        null=False,
        verbose_name=_('código del país'))
    nombre_pais = models.CharField(
        max_length=250,
        blank=False,
        null=False,
        verbose_name=_('nombre del país'))

    class Meta:
        db_table = 'paises'
        verbose_name = _('Pais')
        verbose_name_plural = _('Paises')

    def __str__(self):
        return self.nombre_pais


class Ciudades(models.Model):
    """
        Modelo para lista de ciudades.
    """
    id_ciudad = models.AutoField(
        primary_key=True,
        blank=False,
        null=False,
        verbose_name=_('código del país'))
    nombre_ciudad = models.CharField(
        max_length=250,
        blank=False,
        null=False,
        verbose_name=_('nombre del país'))
    id_pais = models.ForeignKey(
        Paises,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
        verbose_name=_('país donde se encuentra la ciudad'))

    class Meta:
        db_table = 'ciudades'
        verbose_name = _('ciudad')
        verbose_name_plural = _('ciudades')

    def __str__(self):
        return self.nombre_ciudad


class Proveedores(models.Model):
    """
        Definición de Proveedor.
    """
    id_proveedor = models.AutoField(primary_key=True)
    id_usuario = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True)
    nombre_empresa = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('Empresa'))
    descripcion = models.TextField(
        null=False,
        blank=False,
        verbose_name=_('descripción de la empresa'),
        validators=[
            validators.MinLengthValidator(
                300, message=_('Debe escribir al menos 300 caracteres'))
        ])
    direccion_fiscal = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('dirección Fiscal'))
    pais_direccion_fiscal = models.ForeignKey(
        Paises,
        related_name='pais_direccion_fiscal',
        null=False,
        blank=False,
        default='',
        verbose_name=_('país'))
    ciudad_direccion_fiscal = models.ForeignKey(
        Ciudades,
        related_name='ciudad_direccion_fiscal',
        null=True,
        blank=True,
        default=0,
        verbose_name=_('ciudad'))
    zip_direccion_fiscal = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('codigo postal'))
    direccion_envio = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('dirección para envíos de la empresa'))
    pais_direccion_envio = models.ForeignKey(
        Paises,
        related_name='pais_direccion_envio',
        null=False,
        blank=False,
        default='',
        verbose_name=_('pais'))
    ciudad_direccion_envio = models.ForeignKey(
        Ciudades,
        related_name='ciudad_direccion_envio',
        null=True,
        blank=True,
        default=0,
        verbose_name=_('ciudad'))
    zip_direccion_envio = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('codigo postal'))
    dni_rif_documento = models.CharField(
        max_length=100,
        null=False,
        blank=False,
        db_index=True,
        verbose_name=_('documento de Identificación (DNI)'))
    representante_legal = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('representante'))
    codigo_postal = models.CharField(
        max_length=20,
        null=False,
        blank=False,
        default='',
        verbose_name=_('código de área'))
    logo = models.FileField(
        upload_to='logo_proveedores/',
        null=True,
        verbose_name=_('logo del proveedor'))
    catalogo = models.FileField(
        upload_to='catalogo_proveedores/',
        null=True,
        verbose_name=_('catalogo del proveedor'))
    telefono = models.TextField(
        max_length=200, null=False, blank=False, verbose_name=_('teléfonos'))
    correo = models.EmailField(
        max_length=100,
        null=False,
        blank=False,
        verbose_name=_('correo electrónico'),
        help_text=
        _('Requerido. 30 caracteres o menos. Solamente letras, dígitos y @/./+/-/_.'
          ),
        validators=[
            validators.RegexValidator(
                r'^[\w.@+-]+$',
                _('Ingrese un correo válido. Sólo puede contener letras, números y @/./+/-/_.'
                  )),
        ])
    fecha_registro = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name=_('fecha de registro'))
    es_disenador = models.BooleanField(
        blank=False,
        default=False,
        verbose_name=_('Indica si el proveedor es diseñador'))
    nombre_disenador = models.CharField(
        max_length=250,
        null=True,
        blank=True,
        default='',
        verbose_name=
        _('descripción alternativa si el nombre de proveedor es distinto de la marca'
          ))
    activo = models.BooleanField(
        blank=False, default=True, verbose_name=_('activo'))

    class Meta:
        db_table = 'proveedores'
        verbose_name = 'proveedor'
        verbose_name_plural = 'proveedores'

    def __str__(self):
        return self.nombre_empresa


class CuentasPagar(models.Model):
    """Definición de Cuentas por pagar."""

    id_cuenta_pagar = models.AutoField(primary_key=True)
    id_proveedor = models.ForeignKey(
        Proveedores,
        null=False,
        blank=False,
        default=0,
        verbose_name=_('Proveedor Relacionado'))
    id_recepcion = models.IntegerField(
        null=False,
        blank=False,
        default=0,
        verbose_name=_('Recepcion Relacionada'))
    concepto = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        verbose_name=_('Descripción del Compromiso de Pago'))
    tipo_transaccion = models.CharField(
        max_length=15,
        null=False,
        blank=False,
        verbose_name=_('Tipo de Transacción'))
    numero_documento = models.CharField(
        max_length=100,
        null=False,
        blank=False,
        verbose_name=_('Número del Compromiso de Pago'))
    numero_control = models.CharField(
        max_length=100,
        null=False,
        blank=False,
        default=0,
        verbose_name=_('Número de control de la Factura'))
    fecha_documento = models.DateField(
        editable=True, verbose_name=_('Fecha del Documento'))
    fecha_vencimiento = models.DateField(
        editable=True, verbose_name=_('Fecha de Vencimiento'))
    fecha_registro = models.DateField(
        auto_now_add=True, editable=False, verbose_name=_('Fecha de Registro'))
    subtotal = models.DecimalField(
        max_digits=19,
        decimal_places=3,
        default=0.0,
        verbose_name=_('subtotal de factura'))
    monto = models.DecimalField(
        max_digits=19,
        decimal_places=3,
        default=0.0,
        verbose_name=_('Monto del Compromiso'))
    saldo = models.DecimalField(
        max_digits=19,
        decimal_places=3,
        default=0.0,
        verbose_name=_('Saldo del Compromiso'))
    impuesto = models.DecimalField(
        max_digits=19,
        decimal_places=3,
        default=0.0,
        verbose_name=_('Monto de Impuesto'))
    porcentaje_impuesto = models.DecimalField(
        max_digits=19,
        decimal_places=3,
        default=0.0,
        verbose_name=_('Porcentaje de Impuesto'))
    monto_flete = models.DecimalField(
        max_digits=19,
        decimal_places=3,
        default=0.0,
        verbose_name=_('Monto por Flete'))
    porcentaje_flete = models.IntegerField(
        default=0.0, verbose_name=_('Porcentaje por Flete'))
    id_usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        verbose_name=_('Usuario que Registra el Compromiso'))
    estado = models.CharField(
        max_length=10,
        null=False,
        blank=False,
        verbose_name=_('Estado del Compromiso'))

    class Meta:
        db_table = 'cuentas_por_pagar'
        verbose_name = 'Cuenta por Pagar'
        verbose_name_plural = 'Cuentas por Pagar'


class TiposPagos(models.Model):
    """ Definicion del tipo de transaccion que puede tener un Pago."""

    id_tipo_pago = models.AutoField(primary_key=True)
    descripcion = models.CharField(
        max_length=60,
        null=False,
        blank=False,
        default='',
        verbose_name=_('Descripcion del tipo de pago'))

    class Meta:
        db_table = 'tipos_pagos'
        verbose_name = 'tipo de pago'
        verbose_name_plural = 'tipos de pagos'

    def __str__(self):
        return self.descripcion


class Pagos(models.Model):
    """ Definición de un pago de factura."""

    id_pago = models.AutoField(primary_key=True)
    id_cuenta_pagar = models.ForeignKey(
        CuentasPagar,
        null=True,
        blank=True,
        verbose_name=_('Cuenta por Pagar que se Cancela'))
    concepto = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='CANCELACION DE FACTURA: ',
        verbose_name=_('Descripción del Pago'))
    tipo = models.ForeignKey(
        TiposPagos, null=False, blank=False, verbose_name=_('Tipo de Pago'))
    monto = models.DecimalField(

apps/cuentas_pagar/templates/cuentas_pagar_listar.html
{% extends 'base.html' %} {% block contenido %}
<div class="panel panel-primary panel-vima">
    <div class="panel-heading">Listado de Cuentas Por Pagar</div>
    {% if listado_deuda %} 
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <td>Nro.</td>
                    <td>Proveedor</td>
                    <td>Deuda Total</td>
                    <td>Saldo adeudado</td>
                    <td>Cantidad de facturas</td>
                    <td style="text-align: center">Opciones</td>
                </tr>
            </thead>
            <tbody>
                {% for item in listado_deuda %}
                <tr>
                    <td>{% if paginated %}
                            {{ page.start_index | add:forloop.counter }}
                        {% else %}
                            {{ forloop.counter }}
                        {% endif %}</td>
                    <td>{{ item.id_proveedor_id__nombre_empresa }}</td>
                    <td>{{ item.total_monto | floatformat:2 }}</td>
                    <td>{{ item.total_saldo | floatformat:2 }}</td>
                    <td>{{ item.facturas }}</td>
                    <td style="text-align: center"><a href="{% url 'cuentas_pagar:buscar_deuda_proveedor' item.id_proveedor_id %}">Ver Detalle</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %} {% if is_paginated %}
    <div class="text-center">
        <ul class="pagination nav navbar-nav">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
            {% endif %} {% for page in page_obj.paginator.page_range %}
            <li class="{% if page_obj.number == page  %}active{% endif %}">
                <a href="?page={{page }}">{{ page }}</a></li>
            {% endfor %} {% if page_obj.has_next %}
            <li> <a href="?page={{ page_obj.next_page_number }}">Siguiente</a></li>
            {% endif %}
        </ul>
    </div>
    {% endif %}
</div>

{% endblock %}

apps/cuentas_pagar/templates/form_pagar.html
{% extends 'base.html' %}
{% block contenido %} 
{% include 'form_pagar_modal.html' %}
{% endblock contenido %}

apps/cuentas_pagar/templates/form_pagar_modal.html
{% if form.errors %}
	<div id="errors">
		<div class="alert alert-danger">
			<p>Se encontraron errores en la información sumimistrada,por favor corregir lo siguiente:</p>
			<strong>{{ form.non_field_errors }}</strong>
			<ul>
				{% for field in form %}
					{% if field.errors %}<li><strong>{{ field.label }}:</strong> {{ field.errors|striptags }}</li>{% endif %}
				{% endfor %}
			</ul>
		</div>
	</div>
{% endif %}
<form class="form-horizontal" id="form-procesar-pago" action="{% url 'cuentas_pagar:cancelar_deuda_proveedor' id_cuenta %}" method="post">
    {% csrf_token %}
    <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
            <label for="{{form.concepto.name}}">{{form.concepto.label}}</label>{{form.concepto}}
        </div>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
            <label for="{{form.tipo.name}}">{{form.tipo.label}}</label> {{form.tipo}}
        </div>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
            <label for="{{form.monto.name}}">{{form.monto.label}}</label> {{form.monto}}
        </div>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
            <label for="{{form.referencia.name}}">{{form.referencia.label}}</label> {{form.referencia}}
        </div>
    </div>
</form>

apps/cuentas_pagar/templates/proveedores_crear.html
{% extends 'base.html' %} {% load staticfiles %} {% block css %}
<style type="text/css">
    .cargar {
        background: url('{% static 'images/botonadjuntalogo.png' %}')no-repeat;
        height: 28px;
        overflow: hidden;
        cursor: pointer;
    }

    .cargar_catalogo {
        background: url('{% static 'images/website/botonadjuntar_CATALOGO.png' %}')no-repeat;
        height: 28px;
        overflow: hidden;
        cursor: pointer;
    }

    .file-upload {
        opacity: 0;
        border: none;
        height: 100%;
        max-width: 100%;
        color: #ffffff !important;
        cursor: pointer;
    }

    #id_es_disenador {
        list-style: none;
        padding: 0;
    }

    #id_es_disenador input[type=radio] {
        height: 10px;
    }
</style>
{% endblock css%} {% block contenido %} {% if form.errors %}
<div id="errors">
    <div class="alert alert-danger">
        <p>Se encontraron errores en la información sumimistrada, por favor corregir lo siguiente:</p>
        <strong>{{ form.non_field_errors }}</strong>
        <ul>
            {% for field in form %} {% if field.errors %}
            <li><strong>{{ field.label }}:</strong> {{ field.errors|striptags }}</li>{% endif %} {% endfor %}
        </ul>
    </div>
</div>
{% endif %}
<div class="panel panel-primary panel-vima">
    <div class="panel-heading">Crear nuevo proveedor</div>
    <form method="post" enctype="multipart/form-data" class="form-group">
        <div class="row">
            {% csrf_token %}
            <div class="col-md-4">
                <div class="form-group">
                    <label for="{{form.nombre_empresa.name}}">{{form.nombre_empresa.label}}</label> {{form.nombre_empresa}}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="{{form.nombre_disenador.name}}">Nombre de Marca</label> {{form.nombre_disenador}}
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="{{form.dni_rif_documento.name}}">{{form.dni_rif_documento.label}}</label> {{form.dni_rif_documento}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="{{form.representante_legal.name}}">{{form.representante_legal.label}}</label> {{form.representante_legal}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="{{form.correo.name}}">{{form.correo.label}}</label> {{form.correo}}
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label for="{{form.descripcion.name}}">{{form.descripcion.label}}</label> {{form.descripcion}}
                </div>
            </div>
            <fieldset>
                <legend>Dirección Fiscal</legend>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.direccion_fiscal.name}}">{{form.direccion_fiscal.label}}</label> {{form.direccion_fiscal}}
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.pais_direccion_fiscal.name}}">{{form.pais_direccion_fiscal.label}}</label> {{form.pais_direccion_fiscal}}
                    </div>
                </div>
                <div class="col-md-3 col-sm-12">
                    <div class="form-group">
                        <label for="ciudad_direccion_fiscal">Ciudad</label>
                        <select class="form-control" name="ciudad_direccion_fiscal" id="ciudad_direccion_fiscal" nombre_etiqueta="ciudad_fiscal"
                            required>

                        </select>
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.zip_direccion_fiscal.name}}">{{form.zip_direccion_fiscal.label}}</label> {{form.zip_direccion_fiscal}}
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <legend>Dirección de Envío</legend>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.direccion_envio.name}}">{{form.direccion_envio.label}}</label> {{form.direccion_envio}}
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.pais_direccion_envio.name}}">{{form.pais_direccion_envio.label}}</label> {{form.pais_direccion_envio}}
                    </div>
                </div>
                <div class="col-md-3 col-sm-12">
                    <div class="form-group">
                        <label for="ciudad_direccion_envio">Ciudad</label>
                        <select class="form-control" name="ciudad_direccion_envio" id="ciudad_direccion_envio" nombre_etiqueta="ciudad_envio" required>

                        </select>
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.zip_direccion_envio.name}}">{{form.zip_direccion_envio.label}}</label> {{form.zip_direccion_envio}}
                    </div>
                </div>
            </fieldset>
            <div class="col-md-4 ">
                <div class="form-group">
                    <label for="{{form.logo.name}}">{{form.logo.label}}</label>
                    <div class="cargar">{{form.logo}}</div>
                    <div class="clearfix" style="height: 6px;"></div>
                    <div style="margin:0 auto; width: 80%">
                        <img name="preview_logo" />
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="{{form.catalogo.name}}">{{form.catalogo.label}}</label>
                    <div class="cargar_catalogo">{{form.catalogo}}</div>
                    <div class="clearfix" style="height: 6px;"></div>
                    <div style="margin:0 auto; width: 80%">
                        <img name="preview_catalogo" />
                        <div class="titulo_pdf"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    {{form.es_disenador.label}}
                </div>
                <div class="form-group">
                    <label for="{{form.es_disenador.name}}">{{form.es_disenador}}</label>
                </div>
            </div>
            <fieldset>
                <legend> Datos para acceder al sistema </legend>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="usuario">Usuario para Designer Lounge</label>
                        <input type="text" name="usuario_proveedor" class="form-control" required id="usuario_proveedor">
                    </div>
                </div>
                <!-- datos usuario  -->
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="password1">Indique una contraseña</label>
                        <input type="password" id="password1" name="password1" class="form-control" required></input>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="password2">Repetir la contraseña</label>
                        <input type="password" name="password2" id="password2" class="form-control" required></input>
                    </div>
                </div>
            </fieldset>
            <div class="col-xs-7 col-sm-4 col-sm-offset-2 col-md-3 col-md-offset-3 col-lg-3 col-lg-offset-3"><button style="width: 94px;float: right;" class="btn btn-primary" type="submit">Guardar</button></div>
            <div class="col-xs-5 col-sm-6 col-md-6 col-lg-6 "><a class="btn btn-primary" href="{% url 'cuentas_pagar:listar_proveedores' %}" style="height: 34px;width: 85px;">Volver</a></div>
        </div>
    </form>
</div>
{% endblock contenido %}
{% block js %}
<script type="text/javascript">
    $(function (){
        $("#id_pais_direccion_fiscal").on('change', function () {
            fillCities('{{csrf_token}}','#ciudad_direccion_fiscal', $('#id_pais_direccion_fiscal').val());
        });

        $("#id_pais_direccion_envio").on('change', function () {
            fillCities('{{csrf_token}}','#ciudad_direccion_envio', $('#id_pais_direccion_envio').val());
        });
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            if (input.name == "logo") {
                if ((input.files[0].type != 'image/png') && (input.files[0].type != 'image/jpg') && (input.files[0].type != 'image/jpeg')) {
                    mostrarMensajes('Sólo se permiten imágenes en formato PNG o JPG');
                    $('#id_logo').val('');
                    return false;
                }
            }
            else {
                if (input.files[0].type != 'application/pdf') {
                    mostrarMensajes('Sólo se permiten archivos PDF');
                    $('#id_catalogo').val('');
                    return false;
                }

            }
            var reader = new FileReader();
            reader.onload = function (e) {
                if (input.name == "logo") {
                    $("img[name='preview_logo']").attr('src', e.target.result).css({ 'width': '100px', 'height': '100px' });
                }
                else {
                    $("img[name='preview_catalogo']").attr('src', "{% static 'images/website/logo_pdf_load.png' %}").css({ 'width': '100px', 'height': '100px' });
                    $('.titulo_pdf').html(input.files[0].name);
                }
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
{% endblock js %}

apps/cuentas_pagar/templates/proveedores_listar.html
{% extends 'base.html' %} {% block contenido %}
<div class="panel panel-primary panel-vima">
    <div class="panel-heading">Listado de Proveedores</div>
    <a class="glyphicon glyphicon-plus btn-nuevo" href="{% url 'cuentas_pagar:crear_proveedores' %}">Nuevo</a>
    <div class="table-responsive">
        <table class="table table-hover">
            {% if proveedores %}
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Descripcion</td>
                    <td>DNI/RIF</td>
                    <td>Teléfonos</td>
                    <td>Correo</td>
                    <td>Activo</td>
                    <td style="text-align: center">Opciones</td>
                </tr>
            </thead>
            <tbody>
                {% for proveedor in proveedores %}
                <tr>
                    <td>{{ proveedor.id_proveedor }}</td>
                    <td>{{ proveedor.nombre_empresa }}</td>
                    <td>{{ proveedor.dni_rif_documento }}</td>
                    <td>{{ proveedor.telefono }}</td>
                    <td>{{ proveedor.correo }}</td>
                    {% if proveedor.activo %}
                    <td>
                        Activo
                    </td>
                    {% else %}
                    <td>
                        Inactivo
                    </td>
                    {% endif %}
                    <td style="text-align: center">
                        <a class="glyphicon glyphicon-pencil" href="{% url 'cuentas_pagar:editar_proveedores' proveedor.id_proveedor %}" />
                        <a class="glyphicon glyphicon-remove" href="{% url 'cuentas_pagar:eliminar_proveedores' proveedor.id_proveedor %}" />
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            {% else %}
            <h3>No Hay Registros de proveedores.</h3>
            {% endif %}
        </table>
    </div>
    {% if is_paginated %}
    <div class="text-center">
        <ul class="pagination nav navbar-nav">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
            {% endif %} {% for page in page_obj.paginator.page_range %}
            <li class="{% if page_obj.number == page  %}active{% endif %}">
                <a href="?page={{page }}">{{ page }}</a></li>
            {% endfor %} {% if page_obj.has_next %}
            <li> <a href="?page={{ page_obj.next_page_number }}">Siguiente</a></li>
            {% endif %}
        </ul>
    </div>
    {% endif %}
</div>
{% endblock %}