apps/administrador/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.cuentas_pagar.views import get_cities_by_countryid

from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^iniciar_sesion/$', iniciar_sesion),
    url(r'^cerrar_sesion/$', cerrar_sesion, name='cerrar_sesion'),
    url(r'^usuario/registro/$', login_required(Usuario_Registro.as_view()), name='usuario_crear'),
    url(r'^usuario/modificar/(?P<pk>\d+)/$',
        login_required(Usuario_Modificacion.as_view()), name='usuario_modificar'),
    url(r'^usuario/listado', login_required(Usuario_Listado.as_view()), name='usuario_listado'),
    url(r'^usuario/eliminar/(?P<pk>\d+)/$',
        login_required(Usuario_Eliminacion.as_view()), name='usuario_eliminar'),
    url(r'^empresa/$', Empresa.as_view(), name='empresa'),
    url(r'^banners/$', Banners, name='banners'),
     url(r'^get_cities/$', get_cities_by_countryid, name='obtener_ciudades'),
#ESTADISTICAS
    url(r'^estadventas/(?P<anno>[^/]+)/(?P<mes>\d+)$',
        login_required(EstadisticasVentas),
        name='estadistica_ventas'),
    url(r'^estadregistros/(?P<anno>[^/]+)/(?P<mes>\d+)$',
        login_required(EstadisticasRegistros),
        name='estadistica_registros'),
    url(r'^estadcategorias/(?P<anno>[^/]+)/(?P<mes>\d+)$',
        login_required(EstadisticasCategorias),
        name='estadistica_registros'),
]

vima/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from apps.administrador.views import cerrar_sesion
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    # url(r'^admin/', admin.site.urls), no se usara el admin de django
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'clave_formulario.html',
        'email_template_name': 'clave_correo.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'clave_enviado.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'clave_confirmar.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'clave_cambiada.html'},
        name='password_reset_complete'),


    url(r'^administrador/', include('apps.administrador.urls', namespace='administrador')),
    url(r'^inventario/', include('apps.inventario.urls', namespace='inventario')),
    url(r'^compras/', include('apps.compras.urls', namespace='compras')),
    url(r'^cuentas_pagar/', include('apps.cuentas_pagar.urls', namespace='cuentas_pagar')),
    url(r'^cerrar_sesion/$', cerrar_sesion, name='cerrar_sesion'),

    url(r'^', include('apps.website.urls', namespace='website'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/administrador/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from apps.cuentas_pagar.models import Paises, Ciudades


def get_full_name(self):
    return '{} {}'.format(self.first_name, self.last_name)


User.add_to_class('__str__', get_full_name)


class Banners(models.Model):
    nombre_archivo = models.CharField(
        max_length=250, verbose_name=_('Nombre archivo'), unique=True)
    nombre_cifrado = models.CharField(
        max_length=250, verbose_name=_('Nombre cifrado'), unique=True)
    path = models.CharField(max_length=250, null=False, blank=False)
    estado = models.BooleanField(default=True, verbose_name=_('Estado'))

    class Meta:
        db_table = 'banners'
        verbose_name = 'Banner'
        verbose_name_plural = 'Banners'


class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.__class__.objects.exclude(id=self.id).delete()
        super(SingletonModel, self).save(*args, **kwargs)

    @classmethod
    def load(cls):
        try:
            return cls.objects.get()
        except cls.DoesNotExist:
            return cls()


class ConfiguracionEmpresa(SingletonModel):
    nombre = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('Nombre de la empresa'))
    direccion_fiscal = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('dirección fiscal'))
    pais_direccion_fiscal = models.ForeignKey(
        Paises,
        related_name='pais_direccion_fiscal_emp',
        null=False,
        blank=False,
        default='',
        verbose_name=_('país'))
    ciudad_direccion_fiscal = models.ForeignKey(
        Ciudades,
        related_name='ciudad_direccion_fiscal_emp',
        null=False,
        blank=False,
        default=0,
        verbose_name=_('ciudad'))
    zip_direccion_fiscal = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('código postal'))
    direccion_envio = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('direccion para envíos'))
    pais_direccion_envio = models.ForeignKey(
        Paises,
        related_name='pais_direccion_envio_emp',
        null=False,
        blank=False,
        default='',
        verbose_name=_('país'))
    ciudad_direccion_envio = models.ForeignKey(
        Ciudades,
        related_name='ciudad_direccion_envio_emp',
        null=False,
        blank=False,
        default=0,
        verbose_name=_('ciudad'))
    zip_direccion_envio = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('código postal'))
    dni_rif_documento = models.CharField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('numero de documento'))
    correo_electronico = models.EmailField(
        max_length=250,
        null=False,
        blank=False,
        default='',
        verbose_name=_('correo electrónico'))
    logo = models.FileField(
        upload_to='logo_empresa/',
        null=True,
        verbose_name=_('logo de la empresa'))

    class Meta:
        db_table = 'configuracion_empresa'
        verbose_name = 'configuración de la empresa'

apps/administrador/views.py
import json

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core import serializers
from django.core.urlresolvers import reverse_lazy
from django.db.models import Count
from django.db.models.functions import ExtractMonth, ExtractYear
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.shortcuts import HttpResponseRedirect, redirect, render
from django.utils.dateparse import parse_date
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from apps.administrador.forms import EmpresaForm, UserCreateForm, UserUpdateForm
from apps.administrador.models import ConfiguracionEmpresa
from apps.inventario.models import Categorias
from apps.website.models import Cliente, DetalleVentas, Ventas

# Create your views here.


def index(request):
    if request.user.is_authenticated():
        return render(request, 'base.html')
    else:
        if request.method == 'POST':
            if iniciar_sesion(request):
                if request.GET:
                    return HttpResponseRedirect(request.GET.get('next'))
                else:
                    return render(request, 'base.html')
            else:
                return render(request, 'usuario_invalido.html')
    return render(request, 'inicio_sesion.html')


def iniciar_sesion(request):
    """Validación de datos de ingreso. Permite solo usuarios con ``is_staff = True``"""
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            if user.is_staff:
                login(request, user)
                return True
            else:
                return False
        else:
            return False


def cerrar_sesion(request):
    logout(request)
    return redirect('/administrador/')


class Usuario_Registro(CreateView):
    model = User
    form_class = UserCreateForm
    template_name = 'usuarios_crear.html'
    success_url = reverse_lazy('administrador:usuario_listado')

    def form_valid(self, form):
        usuario = form.save(commit=False)
        usuario.is_staff = True
        usuario.save()
        return HttpResponseRedirect(
            reverse_lazy('administrador:usuario_listado'))


class Usuario_Modificacion(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'usuarios_modificar.html'
    success_url = reverse_lazy('administrador:usuario_listado')


class Usuario_Listado(ListView):
    model = User
    template_name = 'usuarios_listado.html'
    paginate_by = 20

    def get_queryset(self):
        return User.objects.all().order_by('id')


class Usuario_Eliminacion(DeleteView):
    model = User
    template_name = 'usuarios_eliminar.html'
    success_url = reverse_lazy('administrador:usuario_listado')


def EstadisticasVentas(request, anno, mes):
    fecha1 = parse_date(anno + '-01-01')
    fecha2 = parse_date(anno + '-12-31')
    V = Ventas.objects.filter(
        fecha__gte=fecha1,
        fecha__lte=fecha2).exclude(estado='Pendiente').annotate(
            month=ExtractMonth('fecha')).values('month').annotate(
                count=Count('id_venta')).values('month', 'count')
    meses = []
    cantidades = []
    for ve in V:
        if mes == '0' or mes == str(ve['month']):
            meses.append(ve['month'])
            cantidades.append(ve['count'])

    return HttpResponse(
        json.dumps({
            'mes': meses,
            'cantidad': cantidades
        }),
        content_type="application/json")


def EstadisticasRegistros(request, anno, mes):
    fecha1 = parse_date(anno + '-01-01')
    fecha2 = parse_date(anno + '-12-31')
    V = Cliente.objects.filter(
        fecha_registro__gte=fecha1, fecha_registro__lte=fecha2).annotate(
            month=ExtractMonth('fecha_registro')).values('month').annotate(
                count=Count('id_cliente')).values('month', 'count')
    meses = []
    cantidades = []
    for ve in V:
        if mes == '0' or mes == str(ve['month']):
            meses.append(ve['month'])
            cantidades.append(ve['count'])

    return HttpResponse(
        json.dumps({
            'mes': meses,
            'cantidad': cantidades
        }),
        content_type="application/json")


def EstadisticasCategorias(request, anno, mes):
    cat = Categorias.objects.filter(id_categoria_padre=1)
    dic = {}
    hijos = []
    categorias = []
    cantidades = []
    fecha1 = parse_date(anno + '-01-01')
    fecha2 = parse_date(anno + '-12-31')
    query = DetalleVentas.objects.filter(
        id_venta__fecha__gte=fecha1, id_venta__fecha__lte=fecha2).exclude(
            id_venta_id__estado="Pendiente").query
    query.order_by = ['id_venta']
    listado = QuerySet(query=query, model=DetalleVentas)

    for c in cat:
        cates = Categorias.get_all_children(
            Categorias.objects.get(descripcion=c))
        for t in cates:
            hijos.append(t.descripcion)
        dic.update({c.descripcion: {'hijos': hijos, 'cant': 0}})
        hijos = []
    contador = 0
    for d, v in dic.items():
        for l in listado:
            if l.id_producto.id_categoria.descripcion in v['hijos'] and (
                    mes == '0' or mes == str(l.id_venta.fecha.month)):
                contador = contador + 1
        categorias.append(d)
        cantidades.append(contador)
        contador = 0

    return HttpResponse(
        json.dumps({
            'categorias': categorias,
            'cantidad': cantidades
        }),
        content_type="application/json")


class Empresa(UpdateView):
    template_name = "empresa.html"
    model = ConfiguracionEmpresa
    form_class = EmpresaForm
    success_url = reverse_lazy('administrador:empresa')
    context_object_name = 'configuracion'

    def get_object(self):
        return ConfiguracionEmpresa.load()

def Banners(request):
    if request.method == "POST":
        pass

    return render(request, 'banners.html',)

apps/administrador/templates/banners.html
{% extends 'inicio_sesion.html' %}

{% block center %}
<div class="panel panel-primary" style="position: relative; top: 10px;">
	<div class="panel-heading">Carga de banners</div>
    
</div>
{% endblock %}

apps/administrador/templates/clave_cambiada.html
{% extends 'inicio_sesion.html' %}

{% block center %}

<h4 style="margin-bottom: 55px;">Su contraseña se reestableció correctamente</h4>
<a  class="button_2" href="/administrador/">Iniciar sesión</a>

{% endblock %}

apps/administrador/templates/clave_confirmar.html
{% extends 'inicio_sesion.html' %}

{% block center %}

{% if validlink %}

<p>Nueva contraseña</p>

<form method="post" style="width:30%;margin: auto;">
{% csrf_token %}

{{ form.new_password1.errors }}
<label for="id_new_password1">Nueva contraseña:</label>
{{ form.new_password1 }}

{{ form.new_password2.errors }}
<label for="id_new_password2">Confirme contraseña:</label>{{ form.new_password2 }}
<input type="submit" class="button_2" style="margin-top: 10px;" value="Guardar" />
</form>

{% else %}

<h1 class="text-center">ENLACE INVÁLIDO: ESTE ENLACE YA HA SIDO UTILIZADO</h1>

{% endif %}

{% endblock %}

apps/administrador/templates/clave_enviado.html
{% extends 'inicio_sesion.html' %}

{% block center %}

<h4>Te hemos enviado un correo con un enlace para reestablecer tu contraseña</h4>

{% endblock %}

apps/administrador/templates/email_forgot.html
{% extends 'inicio_sesion_cliente.html' %}

{% block content %}
    <p>Recuperar contraseña</p>

    <form method="post">
        {% csrf_token %}
        <p class="parrafo">Ingresa tu correo y te enviaremos las <br> instrucciones para restaurar tu contraseña.</p>
        <label id="email" for="id_email"> {{ form.email }}</label><br>
        <p class="parrafo">Recuerda revisar tu bandeja de spam.</p>
        <input class="button_2" type="submit" value="RESTABLECER CONTRASEÑA"/>
    </form>

{% endblock %}

apps/administrador/templates/empresa.html
{% extends 'base.html' %} {% load staticfiles %} {% block css%}
<style type="text/css">
    .cargar {
        background: url('{% static 'images/botonadjuntalogo.png' %}')no-repeat;
        height: 28px;
        overflow: hidden;
        cursor: pointer;
    }

    .file-upload {
        opacity: 0;
        border: none;
        height: 100%;
        max-width: 100%;
        color: #ffffff !important;
        cursor: pointer;
    }
</style>
{% endblock css%} {% block contenido %}
<div class="panel panel-primary panel-vima">
    <div class="panel-heading">Configuración de Empresa</div>
    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <label for="{{form.nombre.name}}">{{form.nombre.label}}</label> {{form.nombre}}
                </div>
            </div>
            <div class="col-md-6  col-sm-12">
                <div class="form-group">
                    <label for="{{form.dni_rif_documento.name}}">{{form.dni_rif_documento.label}}</label> {{form.dni_rif_documento}}
                </div>
            </div>
            <div class="col-md-6  col-sm-12">
                <div class="form-group">
                    <label for="{{form.correo_electronico.name}}">{{form.correo_electronico.label}}</label> {{form.correo_electronico}}
                </div>
            </div>
            <fieldset>
                <legend>Dirección Fiscal</legend>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.direccion_fiscal.name}}">{{form.direccion_fiscal.label}}</label> {{form.direccion_fiscal}}
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.pais_direccion_fiscal.name}}">{{form.pais_direccion_fiscal.label}}</label> {{form.pais_direccion_fiscal}}
                    </div>
                </div>
                <div class="col-md-3 col-sm-12">
                    <div class="form-group">
                        <label for="ciudad_direccion_fiscal">Ciudad</label>
                        <select class="form-control" name="ciudad_direccion_fiscal" id="ciudad_direccion_fiscal" required>

                        </select>
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.zip_direccion_fiscal.name}}">{{form.zip_direccion_fiscal.label}}</label> {{form.zip_direccion_fiscal}}
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <legend>Dirección de Envío</legend>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.direccion_envio.name}}">{{form.direccion_envio.label}}</label> {{form.direccion_envio}}
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.pais_direccion_envio.name}}">{{form.pais_direccion_envio.label}}</label> {{form.pais_direccion_envio}}
                    </div>
                </div>
                <div class="col-md-3 col-sm-12">
                    <div class="form-group">
                        <label for="ciudad_direccion_envio">Ciudad</label>
                        <select class="form-control" name="ciudad_direccion_envio" id="ciudad_direccion_envio" nombre_etiqueta="ciudad_envio" required>

                        </select>
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 col-sm-12">
                    <div class="form-group">
                        <label for="{{form.zip_direccion_envio.name}}">{{form.zip_direccion_envio.label}}</label> {{form.zip_direccion_envio}}
                    </div>
                </div>
            </fieldset>
            <div class="col-sm-12 ">
                <div class="form-group">
                    <label for="{{form.logo.name}}">{{form.logo.label}}</label>
                    <div class="cargar">{{form.logo}}</div>
                    <div class="clearfix" style="height: 6px;"></div>
                    <div style="margin:0 auto; width: 80%">
                        <img name="preview_logo" />
                    </div>
                </div>
            </div>
            <div class="col-xs-7 col-sm-4 col-sm-offset-2 col-md-3 col-md-offset-3 col-lg-3 col-lg-offset-3"><button style="width: 94px;float: right;" class="btn btn-primary" type="submit">Guardar</button></div>
            <div class="col-xs-5 col-sm-6 col-md-6 col-lg-6 "><a class="btn btn-primary" href="{% url 'administrador:index' %}" style="height: 34px;width: 85px;">Volver</a></div>
        </div>
    </form>
</div>
{% endblock contenido %}
{% block js %}
<script type="text/javascript">
    $(function () {
        $("#id_pais_direccion_fiscal").on('change', function () {
            fillCities('{{csrf_token}}', '#ciudad_direccion_fiscal', $('#id_pais_direccion_fiscal').val(),'{{form.ciudad_direccion_fiscal.value}}');
        });

        $("#id_pais_direccion_envio").on('change', function () {
            fillCities('{{csrf_token}}', '#ciudad_direccion_envio', $('#id_pais_direccion_envio').val(),'{{form.ciudad_direccion_envio.value}}');
        });

        $("#id_pais_direccion_fiscal, #id_pais_direccion_envio").trigger("change");
    });


    function readURL(input) {
        if (input.files && input.files[0]) {
            if ((input.files[0].type != 'image/png') && (input.files[0].type != 'image/jpg') && (input.files[0].type != 'image/jpeg')) {
                mostrarMensajes('Sólo se permiten imágenes en formato PNG o JPG');
                $('#id_logo').val('');
                return false;
            }
            var reader = new FileReader();
            reader.onload = function (e) {
                $("img[name='preview_logo']").attr('src', e.target.result).css({ 'width': '100px', 'height': '100px' });
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

</script>
{% endblock js %} 

apps/administrador/templates/index.html
{% extends 'base.html' %}

{% block contenido %}
		<h3>DASHBOARD DEL SISTEMA VIMA ADMINISTRATIVO</h3>
		<a href="{% url 'administrador:cerrar_sesion' %}">Salir</a>
{% endblock %}

apps/administrador/templates/inicio_sesion.html
{% load staticfiles %}
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="{% static 'css/style.css' %} ">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/datepicker3.css' %}" rel="stylesheet">
    <script src="{% static 'js/lumino.glyphs.js' %}"></script>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand"  href="#" style="padding: 10px 15px;margin-left:10px;"><img  src="{% static 'images/LOGO-VIMA-100x30-px.png' %}"></a>
					<h3>ADMINISTRADOR DEL SISTEMA</h3>
			</div>
		</div><!-- /.container-fluid -->
	</nav>


	<div class="background ">
		<div class="fondo col-xs-12 col-md-12	">
			<img src="{% static 'images/LogoVimaP.png' %}">
            {% block center %}
			<p>INICIAR SESIÓN</p>
		  <form id="form_sesion" method="post" accept-charset="utf-8">
		    {% csrf_token %}
			<div class="row col-md-offset-4">  
			    <input type="hidden" name="next" value="{{ next }}">
			    <center><label class="col-md-3 col-xs-12">Usuario <br>
			    <input type="text" name="username" required = "required" placeholder=""></label>
			    <label class="col-md-2 col-xs-12">Contraseña <br>
			    <input type="password" id="password" name="password" required = "required" placeholder=""><br></label></center>
	     	</div>  
			    <div class="clearfix"></div>
			    <a class="link" href="{% url 'password_reset' %}">¿Olvidó la contraseña?</a><br>
			    <input class="button" type="submit" value="INICIAR SESIÓN" id="btn_ingresar">
		   
		  </form>
		 {% endblock %}
		</div>
 	 </div>

</body>
</html>

apps/administrador/templates/modales.html
{% load staticfiles %}

<div id="mensajes" class="modal fade" role="dialog"  tabindex="-1" aria-labelledby="mensajes" aria-hidden="true" style="top: 20%;" >
  <div class="modal-dialog" role="document" style="width: 355px;">
    <div class="modal-content" style="float: left;width: 355px;">
      <div class="modal-body" style="width: 92%; margin: 19px auto 0px; min-height: 83px; max-height: 200px;">
          <span class="glyphicon glyphicon-info-sign" aria-hidden="true" style="float: left; font-size: 23px; width: 11%;"></span>
          <div id="msg" style="text-align: justify; width: 89%; float: left;"></div>

      </div>
      <div class="modal-footer" style="float: left; width: 100%;">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Aceptar</button>
      </div>
    </div>
  </div>
</div>

apps/administrador/templates/usuario_invalido.html
{% load staticfiles %}
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="{% static 'css/style.css' %} ">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/datepicker3.css' %}" rel="stylesheet">
    <script src="{% static 'js/lumino.glyphs.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand"  href="#" style="padding: 10px 15px;margin-left:10px;"><img  src="{% static 'images/LOGO-VIMA-100x30-px.png' %}"></a>
                    <h3>ADMINISTRADOR DEL SISTEMA</h3>
            </div>
        </div><!-- /.container-fluid -->
    </nav>


    <div class="background">
        <div class="fondo">
            <img src="{% static 'images/LogoVimaP.png' %}">
            {% block center %}
            <h5 class="alert alert-danger">El usuario es invalido, o no tiene permiso de acceso. Ingrese nuevamente.</h5>
            <a href="/cerrar_sesion/" class="button">Ingresar</a>
            {% endblock %}
        </div>
     </div>

</body>
</html>

apps/administrador/templates/usuarios_eliminar.html
{% extends 'base.html' %}

{% block contenido %}
<div class="panel panel-primary" style="position: relative; top: 10px;">
    <div class="panel-heading">Confirmar Eliminación</div>
		<form method="post" style="text-align: center;">
			{% csrf_token %}
			<div class="alert alert-warning" style="width: 50%;margin: auto;margin-top: 14px;">
				<h4>¿Está seguro que desea eliminar el registro?</h4>
				<button class="btn btn-primary" type="submit">Si</button>
				<a class="btn btn-default" href="{% url 'administrador:usuario_listado' %}">No</a>
			</div>
		</form>
	</div>		
{% endblock %}

apps/administrador/templates/usuarios_listado.html
{% extends 'base.html' %}


{% block contenido %}
<div class="panel panel-primary" style="position: relative; top: 10px;">
        <div class="panel-heading">Listado de Usuarios</div>
            <a class="glyphicon glyphicon-plus btn-nuevo"  href="{% url 'administrador:usuario_crear' %}">Nuevo</a>
    <div  class="table-responsive">
            <table class="table table-hover">
            {% if object_list %}
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Nombre</td>
                        <td>Apellidos</td>
                        <td>Correo</td>
                        <td>Usuario</td>
                        <td>Estado</td>
                        <td>Opciones</td>
                    </tr>
                </thead>
                <tbody>
                    {% for user in object_list %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.username }}</td>
                        {% if user.is_active %}
                            <td>
                                Activo
                            </td>
                        {% else %}
                            <td>
                                Inactivo
                            </td>
                        {% endif %}
                        <td style="text-align: center;">
                            <a class="glyphicon glyphicon-pencil" href="{% url 'administrador:usuario_modificar' user.id %}" title="Editar"></a>
                            <a class="glyphicon glyphicon-remove" href="{% url 'administrador:usuario_eliminar' user.id %}" title="Eliminar"></a>
                        </td>
                    {% endfor %}
                </tbody>
            </table>
    </div>
            {% if is_paginated %}
        <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                  {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
        </ul>
    {% endif %}
                {% else %}
                    <h1>No Hay Registros de Usuarios.</h1>
                {% endif %}
        </div>

{% endblock %}